# See https://pre-commit.com for more information
# about configuration options

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [
          # SOMEDAY: Uncomment the following line to enforce a maximum line length of 88 characters
          # "--max-line-length=88"
          "--max-line-length=154"
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.2.6
    hooks:
      - id: pylint
        language: system
        args: ["--rcfile=.pylintrc"]

  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: poetry run pytest
        language: system
        types: [python]
        stages: [push]
